### ISSUE TITLE
Bundle optimisation thread

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#117]
The bundle size is getting pretty hefty. We should have a good look at what we are actually exporting. Because it seems way too big for what we are building (1.3mb currently).

Few thing to investigate:
- Alternatives for inlined svg's. These are now all imported once you import the Icon component.
- Look at declaring react as an external in package.json. I think we are somehow still shipping react + react-dom even though it is a peerDependency.

**Comment by CarloPalinckx** [comment]
For now I am taking the following steps to get some insight:

- Upgrade to webpack 4
- Scout out how feasible babel 7 is right now (mostly the --isolatedModules flag)
- Get some profiling and charts up of the bundle.

**Comment by CarloPalinckx** [comment]
This zip contains 2 reports of the baseline ⤵️ 

[Baseline.zip](https://github.com/MyOnlineStore/bricks/files/2273037/Baseline.zip)

**Comment by CarloPalinckx** [comment]
Inclusion of enzyme might be related to us also shipping test.d.ts/story.d.ts

**Comment by woutsluiter** [comment]
The hunt is on 🔫

**Comment by CarloPalinckx** [comment]
Follow progress -> #149
