### ISSUE TITLE
Implement Box as a general layout component 

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#119]
Imo the `Spacer` has gotten a bit redundant because of the `Box` maybe we could just implement the same `offset` `offsetType` interface into the `Box` so we can deprecate the `Spacer`. We could turn the `Box` component into a general positioning/Layout component which also includes a few extra props: 

- width
- minWidth
- maxWidth
- height
- minHeight

**Comment by woutsluiter** [comment]
We could go all in and also add `maxWidth` & `maxHeight`

**Comment by woutsluiter** [comment]
Oh wait it already has `height` & `maxHeight`

**Comment by woutsluiter** [comment]
I would opt for `margin` & `padding` prop for clarity. It already has a `margin` and all other props are css properties which makes it more predictable

**Comment by CarloPalinckx** [comment]
Fair enough, If it has the same TrblType we will be okay in terms of spacing anyway 👍
