### ISSUE TITLE
Deprecate Spacer

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#120]
See the conversation over here: https://github.com/MyOnlineStore/bricks/issues/119

The `Spacer` will be deprecated in favour of `Box` which now has a `margin` and `padding`  for this.

Left to do:
- [x] remove internal usage of `Spacer` (#129)
- [x] deprecation warning added to storybook  (#132)
- [ ] decide on a deprecation version

**Comment by hborghols** [comment]
merged in #245
