### ISSUE TITLE
Remove transform from Button to prevent ugly Safari font antialiasing

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#130]
**Problem**
Button has ugly font antialiasing in Safari.
![image](https://user-images.githubusercontent.com/10552400/43398179-92c6ce34-9407-11e8-84bb-6ba0b26c5d15.png)

**Cause**
`translate3d` without forcing font-smoothing.

**Proposed solution**
Adding font-smoothing seems to change the look of the visual thickness of the Button too much. Removing the `transform` property from the idle state fixes it aswel with the only drawback that Safari still has ugly font antialiasing between states.

**Comment by robinvdv12** [comment]
According to [this](http://files.christophzillgens.com/webkit-font-smoothing.html) artcile, we could add `-webkit-font-smoothing` CSS rule to the button. Resulting in:

![image](https://user-images.githubusercontent.com/28292410/44467328-e3751480-a622-11e8-8984-07b7b16f4716.png)
Without CSS rule

![image](https://user-images.githubusercontent.com/28292410/44467898-58951980-a624-11e8-848b-34ee07fb3e20.png)
With `-webkit-font-smoothing: subpixel-antialiased`

![image](https://user-images.githubusercontent.com/28292410/44467344-f25bc700-a622-11e8-8c3a-6d8525a01d53.png)
With `-webkit-font-smoothing: antialiased`

**Comment by woutsluiter** [comment]
Thing is that alters the visual thickness too much and with that it's readability. You'd have to change the weight (600 instead of 400). But that too has a pretty big impact on the look of the buttons. If UX is ok with that than that would be the best solution. Otherwise I would go with the proposal.

**Comment by hborghols** [comment]
Talk to design about anti-aliasing as this is also an issue with the legibility of light text

**Comment by CarloPalinckx** [comment]
@woutsluiter @robinvdv12  is this still an issue?

**Comment by woutsluiter** [comment]
Sadly yes, it is. But still an acceptable solution IMO would be to remove the `translate3D` value on idle state.
