### ISSUE TITLE
Upgrade to Storybook 4.0

### ISSUE THREAD

**Issue by robinvdv12** [MyOnlineStore/bricks#161]
### Description of the problem ⚡️
I tried to add more documentation about the Bricks Components to the stories. But there are a couple of bugs in storybook 4.0 alpha version. The bugs i've faced so far are:

- The markdown feature in 4.0 alpha is still a little buggy. For example: adding a breakline in markdown will result in a "code-block" which contains all the content after the breakline. Related issue at storybook [here](https://github.com/storybooks/storybook/issues/3759).

- Toggle the `source` setting to `true` will result in a code-block containing the decorator source code instead of the component source code. Issue at storybook [here](https://github.com/storybooks/storybook/issues/4018).

- We need to run the built in chromium in CircleCI to get visual regression test up and running, however running a custom chromium executable is only supported in 4.x.x #171 needs to be made compatible with 4.x.x

**Comment by CarloPalinckx** [comment]
This is being worked on in #163

**Comment by CarloPalinckx** [comment]
Resolved in #286
