### ISSUE TITLE
HOC's for Generic styling components

### ISSUE THREAD

**Issue by nicokoelewijn** [MyOnlineStore/bricks#165]
### Is your feature request related to a problem? Please describe ⚡️
There should be different depth levels, which is currently implemented with components like Raised and Tile. But these components get in the way. And nesting hell would be inevitable. 

### Describe the solution you'd like ✨
A better solution to this problem would be to make this behaviour optional with HOC's. 

### Describe alternatives you've considered 🎡
Another option would be to add this behaviour to the Box component. But the Box already has a lot of functionalities. Making this component any bigger wouldn't be a good thing. We don't want monster components. 

### Additional context 🖼
`withRaised(Box)` would add the styling and props to the Box when it's required.

**Comment by CarloPalinckx** [comment]
I like this, basically we could make a lot of generic styles composable to avoid extra html elements. This comes in handy when html requires a certain nesting pattern. (table> tbody > tr > td) for instance. It is pretty hard to apply generic styles to that since components like `Raised` and `Tile` all come with their own `div`. With a set like this:

```ts
type RaisedProps {
    level: number;
}

withRaised(wrapped);
```

```ts
type BoxProps {
    grow: number;
    wrap: boolean;
    etc...
}

withBox(wrapped);
```

```ts
type AnimationProps {
    show:boolean;
    animation: 'zoom' | 'fade';
}

withAnimation(wrapped);
```
You could compose all these on a `tr` if you wanted.

**Comment by nicokoelewijn** [comment]
Another way to go would be to introduce the trbl to the components like `<StyledToaster margin={trbl(1, 4)}>`. This combined with the `trbl()` having values like 1, 2, 3 etc. This would create a structure that represents the relative proportions. This makes the system more flexible for and the proportions are sort of theme-able because it would be very easy to change them. Using the trbl directly on components would also prevent having to add extra boxes just for styling in some cases.

**Comment by CarloPalinckx** [comment]
Closing this along with #202 due to inactivity. like the PR, we'll let this resurface in due time.
