### ISSUE TITLE
Textfield input (currency)

### ISSUE THREAD

**Issue by nicokoelewijn** [MyOnlineStore/bricks#186]
### Bricks version 📦
0.1.0

### Describe the bug 🔍
When the value of the currency is edited, the cursor will be moved to the end of the input. This is likely caused by the regex that removes the dot in large numbers, this behaviour is also caused by filling in a character. 

### To Reproduce 💥
1. Go to Bricks > Textfield > currency
2. Fill in a character anywhere (not the end) in the string

1. Go to Bricks > Textfield > currency
2. fill the input with `100000`
3. blur the input
4. add a number to the string. 

### Expected behavior ✨
The cursor should stay at the right position. 
Another solution could be to remove the dot(s) on focus.

**Comment by hborghols** [comment]
Nice find, removing the dots on focus is not a bad solution (as long as it's only the thousand separators and not the decimal separator) I think. I'm not sure which solution is easier to implement.
