### ISSUE TITLE
Make FormRow styling more flexible with grow and margin props

### ISSUE THREAD

**Issue by hborghols** [MyOnlineStore/bricks#191]
### Is your feature request related to a problem? Please describe ⚡️
The current implementation of `FormRow` does not allow me to have small labels and large fields, because both of their `flex-grow`'s are set to 1, they take up equal space. I would like to have smaller labels so I have more space in my fields. Additionally, the margins between rows are huge which is very inefficient use of space.

### Describe the solution you'd like ✨
Two props: `label-grow` and `field-grow` that set the respective flex-grow properties for the label and field, allowing you to optionally change the ratio between them. These can default to 1. 

Additionally a margin prop could be added to adjust the margin. Or the margin could be left out completely leaving the margin to the capable hands of a user with a `Box`

### Additional context 🖼

current situation:
![screen shot 2018-09-11 at 17 21 52](https://user-images.githubusercontent.com/23050817/45369881-38cf9080-b5e7-11e8-9011-8828fa39211b.png)

The future I envision:
![screen shot 2018-09-11 at 17 22 55](https://user-images.githubusercontent.com/23050817/45369922-57ce2280-b5e7-11e8-9e23-4ee1cc59a39e.png)

**Comment by CarloPalinckx** [comment]
I don't think I really agree with this proposal. The FormRow was added to create a consistent layout for forms that cannot be deviated from. The labelGrow and fieldGrow seems very much like a design escape-hatch. I think this issue is actually a design-issue instead of a shortcoming of the FormRow.

**Comment by hborghols** [comment]
Won't do. The `FormRow` appears not to be implemented correctly yet so changes will be made to it to create a somewhat different, standardized layout.
