### ISSUE TITLE
Add eventListeners to Popover for internal isOpen state

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#196]
### Is your feature request related to a problem? Please describe ⚡️
Managing the Popover `isOpen` state every time seems redundant for simple hover & click behavior. 

### Describe the solution you'd like ✨
We could manage the `isOpen` state internal and pass a `eventType` prop with a `click` or `hover` component. For external control the internal state could be overwritten by the `isOpen` prop.

### Describe alternatives you've considered 🎡
A separate `ToolTip` component, but that seems a bit overkill for just adding event listeners. 

### Additional context 🖼
The only use case of the Popover so far is the NotificationCenter, which needs the external isOpen state for a callback on close. Managing multiple Popovers in a container that don't need special behavior generates duplicate code.

**Comment by hborghols** [comment]
This seems logical and saves adding a bunch of extra logic every time `Popover` is used.  I guess the following features would need to be implemented:

- When `eventType === 'click'`, it should function as it does now. Having a clickable anchor that opens and closes `Popover`
- When `eventType === 'hover'`, `Popover` should open on mouseEnter and close on mouseExit.
- We should implement click on close outside.

**Comment by woutsluiter** [comment]
Another option is to pass a callback prop and not manage the isOpen state externally at all.

**Comment by CarloPalinckx** [comment]
Maybe instead of `eventType` you could maybe consider something like `triggerOn` or `trigger`.

```js
<Popover triggerOn="hover">
.....
</Popover>
```js

This looks pretty declarative imo.

How would you handle a mismatch on props vs state on the isOpen prop? You could make it either controlled when `isOpen !== undefined` or self-controlled when `isOpen === undefined`.

**Comment by CarloPalinckx** [comment]
> Another option is to pass a callback prop and not manage the isOpen state externally at all.

It probably should always have the option to be controlled. You might want to close it remotely when you open a modal on top of it for instance.

**Comment by hborghols** [comment]
Yeah something like `triggerOn`or `trigger` works for me. We could make that the prop and then an `eventType` enum maybe to define the options.

> How would you handle a mismatch on props vs state on the isOpen prop? You could make it either controlled when isOpen !== undefined or self-controlled when isOpen === undefined.

Either option is fine I guess. I have a slight preference for controlled when `isOpen !==undefined` as it makes internal control the preferred usage.

> It probably should always have the option to be controlled. You might want to close it remotely when you open a modal on top of it for instance.

Agreed

**Comment by woutsluiter** [comment]
> How would you handle a mismatch on props vs state on the isOpen prop
I would go for `isOpen !==undefined`

> It probably should always have the option to be controlled.
Yeah on second thought I agree as well

**Comment by woutsluiter** [comment]
triggerOn seems like a good name

**Comment by hborghols** [comment]
Sweet, I think we can move this over from `RFC` to `To Do` then?

**Comment by CarloPalinckx** [comment]
You might also consider logging a warning when someone uses `isOpen` alongside `triggerOn` btw. But sounds good 👍

**Comment by hborghols** [comment]
Yep, not a bad idea
