### ISSUE TITLE
Apply nesting to ThemeType

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#20]
We need to define the shape/pattern for theme settings so it's clear and predicable in use.

Things to consider:
- nesting rules/pattern
- ways of enforcing boundaries on nesting

#### Proposal
https://gist.github.com/woutsluiter/d661a2348b1b2c07f2d42b80d1da8667

**Comment by woutsluiter** [comment]
https://gist.github.com/woutsluiter/d661a2348b1b2c07f2d42b80d1da8667

**Comment by CarloPalinckx** [comment]
related to #33

**Comment by CarloPalinckx** [comment]
Like in the mentioned gist we are thinking of working towards a "component-based" theme setup. This would mean that every component must define its own required theme rules. This makes it more scalable as well. We can also augment storybook to edit these component based rules in something along the lines of knobs.

**Comment by CarloPalinckx** [comment]
We could define a global interface which is merged on by every component that requires its own theme rules. This would look something like:

```
declare global {
    interface Theme {
        button: {
            idle: {
                backgroundColor: '#fff',
            }
        }
    }
}
```

**Comment by woutsluiter** [comment]
nesting rule:
1. Component name
2. Paths (variant/state)
3. CSS properties

**Comment by woutsluiter** [comment]
There should be no global properties, i.e. no global fontSize or fontFamily. Every component has it's own styling. This ensures flexibility. A theme generator could map shared values to individual component theme props.

**Comment by CarloPalinckx** [comment]
So, turns out that global interfaces aren't really the way to go here. We will export a type with a theme for every component. These will be imported in one file that hosts the global type. Same effect but easier to generate declarations from.
