### ISSUE TITLE
Bump React to 16.6

### ISSUE THREAD

**Issue by hborghols** [MyOnlineStore/bricks#200]
### Is your feature request related to a problem? Please describe ⚡️
We want to use new features such as the react profiler!

### Describe the solution you'd like ✨
Upgrade React

### Describe alternatives you've considered 🎡
Not upgrading React

**Comment by woutsluiter** [comment]
I like your solution 👌

**Comment by CarloPalinckx** [comment]
Won't do, Can't reproduce

**Comment by CarloPalinckx** [comment]
Will do, can reproduce

**Comment by hborghols** [comment]
https://reactjs.org/blog/2018/10/23/react-v-16-6.html

16.6 pls
