### ISSUE TITLE
RGB(A) instead of HEX

### ISSUE THREAD

**Issue by nicokoelewijn** [MyOnlineStore/bricks#213]
### Is your feature request related to a problem? Please describe ⚡️
I'd like to suggest changing the hex codes now used in the theme to be converted to RGB values.
The benefit would be that the common .4 alpha for box-shadows can then become a themeable value.

### Describe the solution you'd like ✨
The result would be something like this: 
```
TextField: {
  focus: {
    boxShadow: '0 0 0 4px rgba(green.lighter1, alpha.boxshadow)',
  }
},
```

### Describe alternatives you've considered 🎡
We could keep the settings as they are right now, but i do think the chance of error will be reduced.

**Comment by hborghols** [comment]
I ran into this as well this week. My proposal is to make a `hexToRGB` converter in `utilities` that can be used as follows:

```
Textfield: {
    focus: {
        boxShadow: `0 0 0 4px rgba(${hexToRGB(green.lighter1)}, ${boxshadow.focus})`,
    }
],
```

**Comment by woutsluiter** [comment]
I like the hexToRGB idea. Would be awesome if it could autodetect the value type, so you can guarantee an RGB value no matter how you define it in a theme object
