### ISSUE TITLE
Modal breaks in Firefox

### ISSUE THREAD

**Issue by hborghols** [MyOnlineStore/bricks#222]
### Bricks version 📦
0.5.2

### Describe the bug 🔍
When the Modal has a lot of body content, the content in `renderFixed` is pushed down and out of view in firefox. No issues in chrome.

### To Reproduce 💥
1. Add a lot of content in the body of the modal (with some buttons or whatever attached in `renderFixed` so that scrolling would be necessary.
2. Observe the content of renderFixed going out of view.

### Expected behavior ✨
The `renderFixed` portion of the modal should always remain in place while the body should scroll.

### Screenshots 📸
Without a lot of body content:
![screenshot 2018-10-16 at 17 11 48](https://user-images.githubusercontent.com/23050817/47026825-9d41ba80-d166-11e8-9f53-281e70949a3a.png)

With a lot of body content:
![screenshot 2018-10-16 at 17 12 38](https://user-images.githubusercontent.com/23050817/47026867-b34f7b00-d166-11e8-9882-0f76a9ae478b.png)

### Context👨‍💻
 - Browser: Firefox Developer edition
 - Browser version: 63.0b12 (64-bit)

**Comment by woutsluiter** [comment]
Seems Edge also has this issue
