### ISSUE TITLE
Modal is always stretched to it's maximum height

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#231]
### Bricks version 📦
0.6.0 (https://github.com/MyOnlineStore/bricks/pull/223) seems to have introduced this to counteract IE/Edge behavior.

### Describe the bug 🔍
The Modal component always stretches to it's maximum height regardless of its content. It would be nice if we could restore the auto height functionality.

### To Reproduce 💥
1. open the Modal story
2. strip out most of the content
3. remains max height.

### Expected behavior ✨
I would expect that the Modal only uses the space that it needs.

### Screenshots 📸
![screenshot 2018-10-23 at 14 42 02](https://user-images.githubusercontent.com/6347900/47361307-df707c00-d6d1-11e8-8975-6146e3e53afd.png)

### Context👨‍💻
 - Browser chrome

**Comment by woutsluiter** [comment]
Should be thoroughly tested with short and long (scrollable) content in combination with the fixed button row. The problem which #223 tried to solve was the button row being pushed out of sight in FF, Edge and IE

**Comment by hborghols** [comment]
Darn'd modal 😑
