### ISSUE TITLE
disabled state for RadioButton and Checkbox

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#233]
### Is your feature request related to a problem? Please describe ⚡️
Sometimes an options availability is dependent on other settings.

### Describe the solution you'd like ✨
A disabled prop which adds the disabled attribute to the input and gives the label a disabled look, like adding the prop `descriptive` to `Text` or giving the whole thing a reduced opacity (discuss with UX).

### Describe alternatives you've considered 🎡
Excluding the option from the list when unavailable. But as user you might want to know that the option is there, just not available in the current configuration.

### Additional context 🖼
![image](https://user-images.githubusercontent.com/10552400/47415079-de435b80-d772-11e8-9d40-a852efece90b.png)

**Comment by hborghols** [comment]
I think descriptive/reduced opacity works but it would be good to have some input from the picture boys (aka UX).

**Comment by woutsluiter** [comment]
Or the zebra striping of course...

**Comment by CarloPalinckx** [comment]
Imo, whacking a disabled state on everything kinda seems like heading the wrong way design wise. Because it creates a ton of visual clutter. Also, I don't think I have ever seen a disabled radio button or a disabled check box (which would be next).  Maybe there is a way we could reconsider this from a design perspective?

**Comment by CarloPalinckx** [comment]
If you properly funnel user through certain choices you wouldn't need to show all the possible outcomes beforehand because they shouldn't apply to them. The alternative you described here seems like the exact thing you would want to do.

**Comment by hborghols** [comment]
I agree that ideally it would not be necessary.

**Comment by woutsluiter** [comment]
Maybe you're right about the clutter and we should definitely aim for less is more. But perhaps it's not a silver bullet. When I expect to find a certain option in a list, it can be confusing/frustrating when the option just isn't there without any explanation why. It might send the user on a wild goose chase which ends in frustration. In that case it would be more obvious to me when it's there but I have to "unlock" it.

**Comment by CarloPalinckx** [comment]
But I think that a giant chain of form elements should never be the tool to show "all the possible options". We try to solve every single problem with giant form's. If there are so much dependable outcomes in a form you should not start by showing a form imo. You should be showing an overview of all the benefits from certain choices and after let users tweak those choices further.

**Comment by hborghols** [comment]
By the way, for context, the culprit that started this discussion: one disabled radiobutton:
![screenshot 2018-10-24 at 10 52 34](https://user-images.githubusercontent.com/23050817/47418753-0d5dcb00-d77b-11e8-82eb-a8693fa54d48.png)

**Comment by woutsluiter** [comment]
I agree that showing full configuration forms when not applicable should be avoided, but that's not what I'm talking about here. In fact, that's already being applied in the MyParcel Settings form (though it could also be applied to the label settings form 🤔). I'm talking about 1 option in a list of lets say 4 options. And again, I agree we should carefully consider hiding it. But it might not always be the way to go.

**Comment by CarloPalinckx** [comment]
After some internal discussion with some extra context I would like to adjust my opinion a bit on this. I think the addition to the component is fine in itself but I do think we could really use some ground rules on usage of "disabled" field so we can avoid using this as an escape hatch for problems that are inherently complex 👍

**Comment by LuukHorsmans** [comment]
There are designs available for this (related to the toggle/radio/checkbox disabled states). The designs just haven't been communicated properly. The new toggle disabled state (+label state) will be applied to checkboxes and radiobuttons aswell.

All states are available in Sketch/Abstract for toggles, checkboxes and radio's.
![image](https://user-images.githubusercontent.com/44433296/47428923-03e15c80-d795-11e8-96c5-830e339d0517.png)

The disabled state for the labels uses the same principle for all of these elements (a lock + a lighter grey label). For the label disabled state specs see:
https://share.goabstract.com/c7c54df1-c923-4897-8cc0-ef760898c5ed

I agree that these should primarily be avoided to reduce visual clutter (the ground rule), but they can exist nonetheless.
