### ISSUE TITLE
Melbourne font doesn't render in storybook when you haven't installed it locally.

### ISSUE THREAD

**Issue by robinvdv12** [MyOnlineStore/bricks#240]
### Describe the bug 🔍
When you doesn't have the "Melbourne" font installed locally. The Heading component doesn't render in "Melbourne", but instead it renders with the font "Arial".

### To Reproduce 💥
1. Make sure you don't have installed the Melboure font, or make sure you de-activate it.
2. Go to the Heading story in Storybook.
3. See the heading in Arial font.

### Expected behavior ✨
The heading should render in Melbourne font, just like the design.

### Screenshots 📸
![image](https://user-images.githubusercontent.com/28292410/47558128-affc8200-d912-11e8-83db-4690bd02858b.png)

**Comment by CarloPalinckx** [comment]
Resolved in #306
