### ISSUE TITLE
Support html attributes on rendered HTML

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#249]
### Is your feature request related to a problem? Please describe ⚡️
Currently you can't set generic html attributes on most components, an exception being `Box`. You wouldn't be able to add a `data-test-id` for instance.

### Describe the solution you'd like ✨
I suggest we provide components with an `attributes` prop that will be spread on the outer element of the component.

### Describe alternatives you've considered 🎡
There is also a suggested spec somewhere where you prefix the element attribute with an `$`, which is not really preferable imo because there are already similar conventions around that use a `$` as well (jQuery, observables).

### Additional context 🖼

We would need some way to extend every component with some sort of a "Base class". We should have a look at how https://rebassjs.org/ does this with its layout properties.

**Comment by hborghols** [comment]
Having generic html attributes would be nice. I guess spreading on the outer element would work. In any case I think we're all traumatized by $ too much to use that ;).

**Comment by woutsluiter** [comment]
So Rebase uses [`styled-system`](https://github.com/jxnblk/styled-system) but that might be overkill. Just spreading the props and typing them as `React.HTMLAttributes` would work I guess.

**Comment by CarloPalinckx** [comment]
Removing this from the 1.0.0 milestone since the most pressing issue "test id's" is resolved with #342

**Comment by CarloPalinckx** [comment]
> Removing this from the 1.0.0 milestone since the most pressing issue "test id's" is resolved with 

Closing this for the same reason
