### ISSUE TITLE
TypeScript 3

### ISSUE THREAD

**Issue by hborghols** [MyOnlineStore/bricks#250]
### Is your feature request related to a problem? Please describe ⚡️
We are still on TypeScript 2.8 but the current version is 3.1 😨. We should think about upgrading some time because **newer === better**. 

### Describe the solution you'd like ✨
New TypeScript

**Comment by CarloPalinckx** [comment]
👍 I've picked up https://github.com/MyOnlineStore/bricks/pull/163 a bit again since sb 4.0. Not much of a hassle to pick this up in there as well.

**Comment by hborghols** [comment]
Cool 😎

**Comment by hborghols** [comment]
This has been added with #251.
