### ISSUE TITLE
TextField IE bugs

### ISSUE THREAD

**Issue by hborghols** [MyOnlineStore/bricks#253]
### Bricks version 📦
0.6.2

### Describe the bug 🔍
There are two bugs: The contents of the input field are not centered vertically and the prefix/suffix are missing in the withCurrency formatting story.

### To Reproduce 💥
1. Open IE11
2. Go to the TextField stories
3. Observe the beautiful rendering of an engine from 5 years ago.

### Expected behavior ✨
Content of the input field are centered and there is a currency prefix/suffix in a currency formatted textfield.

### Screenshots 📸
Vertical centering:
![screenshot 2018-11-07 at 11 54 58](https://user-images.githubusercontent.com/23050817/48127441-fee7d700-e283-11e8-8f0e-8743d97df115.png)

missing prefix:
![screenshot 2018-11-07 at 11 55 45](https://user-images.githubusercontent.com/23050817/48127477-1921b500-e284-11e8-83c8-0216e097ed47.png)

### Context👨‍💻
 - IE11 🤦‍♂️

**Comment by hborghols** [comment]
Update: missing prefix is solved by polyfilling react-intl so this doesn't have to be addressed further currently (although if someone has a clever solution be my guest). The vertical centering is still an issue though (but a small one).

**Comment by CarloPalinckx** [comment]
@hborghols Do you think this issue still plays in the current major version? Otherwise we can close this :)

**Comment by hborghols** [comment]
😅 I have no idea but given the attention this has gotten in the last 1,5 years (both from us and complaints from elsewhere) I think it's save to close it.
