### ISSUE TITLE
Multiple onBlur & onFocus calls on TextField

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#256]
### Bricks version 📦
0.6.2

### Describe the bug 🔍
The `StyledWrapper` captures the blur and focus events and executes the onBlur and onFocus props, while these are already called on the input. So it results in multiple calls. The onFocus is even called a third time due to the onClickCapture.

The good thing about the click capture is that even when you click on a prefix or suffix, the field is focussed. The rest seems unnecessary.

### To Reproduce 💥
1. Go to story of TextField and add a onBlur and onFocus with a console log or something
2. Focus and blur and behold the console.

### Expected behavior ✨
I would expect it to call the onBlur and onFocus once per event. But I would also expect the field to focus when clicking on a prefix. So I would like to suggest to remove the `onBlurCapture` and `onFocusCapture`, but keep the `onClickCapture` to force a focus on the input.

**Comment by hborghols** [comment]
> So I would like to suggest to remove the onBlurCapture and onClickCapture, but keep the onClickCapture to force a focus on the input.

I don't really get this, you want to remove the onClickCapture but you want to keep the onClickCapture? 

Other than that I think it would be good if the events only fired once 👍

**Comment by woutsluiter** [comment]
Oh whoops typo 😅 I mean remove the `onBlurCapture` and `onFocusCapture`, but keep the `onClickCapture`

**Comment by nicokoelewijn** [comment]
Removing the Capture listeners will cause the affixes to become unclickable. Right now it is possible to click the affix and the focus will be set on the input. Another solution would be to remove the focus and blur from the input and only listen on the wrapper. This way the affixes will still be clickable and other ways of focus (like clicking or tabbing) still work.

**Comment by nicokoelewijn** [comment]
Created PR for this: https://github.com/MyOnlineStore/bricks/pull/257
