### ISSUE TITLE
Toaster auto dismissal

### ISSUE THREAD

**Issue by nicokoelewijn** [MyOnlineStore/bricks#259]
### Is your feature request related to a problem? Please describe ⚡️
It would be nice if notifications where to dismiss after the message. This would be an additional prop for the `Toaster`. 
This feature is inspired by the Hubspot alert component (https://canvas.hubspot.com/components/alerts-messaging#floating).
By making this an optional prop, the Toaster will dismiss automatically after x seconds, that way less importat notifications won't have to be closed.  

### Describe the solution you'd like ✨
Add a prop `autoDismiss`. When the time has passed the Toaster would become invisible again. 

### Describe alternatives you've considered 🎡
A different solution would be to create a `dismissTime` prop that would set the time in seconds before the toaster will dismiss. 
I do think that it would be best if the interval  is the same everywhere. 

### Additional context 🖼
Example of how this would work: https://canvas.hubspot.com/components/alerts-messaging#floating, _click the show default notification_

**Comment by hborghols** [comment]
Great 👍! Then the next question is: should a toaster always automatically close after an interval or do we want to keep it optional? In the first case we won't need an extra prop.

**Comment by nicokoelewijn** [comment]
It should only auto dismiss if there is no actions attached to it. An action could be something like a link, button or maybe an ID that can be copied. So an optional prop would definitely be the best option.

**Comment by woutsluiter** [comment]
In the example of hubspot they also linked the behavior to the severity of the notification, i.e. `danger` needs a manual dismiss. Definitely something to consider imo. When something goes wrong, but I was just afk, I'd still like to know what happend. Also, maybe you could turn it around: always dismiss unless a `manualDismiss` is set.

**Comment by woutsluiter** [comment]
I'm certainly all for an extra prop. My point was more UX wise, what should be the default and what is the exact pattern. (you mentioned actions, but I think severity would also be a good candidate). But I guess that's more something you'd apply in the monolith/client.

**Comment by hborghols** [comment]
> Because if we forget to set the set the manualDismiss on an important toaster, it would be really annoying for the user. Imo the toaster should always be on manualDismiss unless the autoDismiss is set.

Good point. Let's go with autoDismiss then if everyone is in favor ✋.
