### ISSUE TITLE
Turn RadioButtonGroup into a general Separated component

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#261]
### Is your feature request related to a problem? Please describe ⚡️
We are currently starting to see patterns in grouping behavior. We support the `RadioButonGroup` at the moment which actually has nothing to do with the `RadioButton` apart from naming 😄  it just maps children in a `Box` and applies padding.

### Describe the solution you'd like ✨
I suggest we turn the `RadioButtonGroup` into a component named `Separated`. This component could provide a general way of visually "grouping" any element. The current RadioButtonGroup only supports margin as saperator. We could later add a visual divider to this. This could also make the MessageStream obsolete (which is nice) and it could possibly solve some issues we are having when using a Checkbox(group) in a FormRow. 

We could optionally allow for a prop to be set that enables/disables the leading separator (be it margin or a divider). We could also look into requiring children to be added (If that is even possible in a sane way). This would prevent people from abusing it to position things instead of using a `Box`

```ts
type Props = {
    by?: 'margin'|'divider'; // divider could be added later
    before?: boolean;
    after?: boolean;
    children: ReactElement
}
```

Would like some ideas for the prop name. I'm not really sure if it the proper name for what it does.

### Describe alternatives you've considered 🎡
We could alternatively double export RadioButtonGroup as CheckBoxGroup

**Comment by hborghols** [comment]
I agree with the suggestion to change `RadioButtonGroup` into a more general component and with the suggested implementation. One small nit: `Separated` is spelled with an `a` 😉. 

I agree that `leading` is not the ideal name for the prop. Maybe something like `ignoreFirstChild`, `noLeadingSeparator` 🤔. The name gets long very quickly. 

In addition to leading we might also need a similar prop for the trailing separator.

**Comment by CarloPalinckx** [comment]
`beforeFirst?: boolean` `afterLast?: boolean` maybe? 🤔

**Comment by CarloPalinckx** [comment]
the opposite of leading would be follow I guess 🤔 
```ts
<Separated leading following>
    <div />
    <div />
</Separated>

**Comment by CarloPalinckx** [comment]
Or why not just:
```ts
<Separated before after>
    <div />
    <div />
</Separated>
```
?

**Comment by woutsluiter** [comment]
`<Separated outer>` `<Separated includeOuter>` `<Separated includeStart includeEnd>`

**Comment by hborghols** [comment]
Trailing singles out the last item whereas following implies every item following the leading item. Anyway, I like before and after. Seems like a nice and simple solution.

**Comment by CarloPalinckx** [comment]
I would invert that tho, I think "in-between" would be used most regularly. Ill make an example with a few options to choose from

**Comment by CarloPalinckx** [comment]
Option A:
```ts
type Props = {
    by?: 'margin'|'divider'; // divider could be added later
    at?: 'top'|'bottom'|'both'
}

<Separated by="divider" at="top">
    <div />
    <div />
</Separated>
```

Option B:
```ts
type Props = {
    by?: 'margin'|'divider'; // divider could be added later
    include?: 'top'|'bottom'|'both'
}

<Separated by="divider" include="top">
    <div />
    <div />
</Separated>
```

Option C:
```ts
type Props = {
    by?: 'margin'|'divider'; // divider could be added later
    before?: boolean;
    after?: boolean;
}

<Separated by="divider" before after>
    <div />
    <div />
</Separated>
```

**Comment by CarloPalinckx** [comment]
I kinda like option C tbh

**Comment by woutsluiter** [comment]
My vote would be Option B

**Comment by hborghols** [comment]
I also kinda like option C tbh

**Comment by CarloPalinckx** [comment]
Inb4 @hborghols : "I like option A"

**Comment by hborghols** [comment]
😄 nope

**Comment by CarloPalinckx** [comment]
@woutsluiter you okay with option C?

**Comment by woutsluiter** [comment]
Option C is alright, but I just don't think it's as declarative as B

**Comment by CarloPalinckx** [comment]
Lets go with C for now. We can always reevaluate this later. Or add a
```ts
<WoutSeparator include="neither">
    <div />
    <div />
</WoutSeparator>
```

😄

**Comment by woutsluiter** [comment]
I'll make my own bricks! With blackjack, and hookers!

**Comment by hborghols** [comment]
🙌

**Comment by CarloPalinckx** [comment]
And without colors!

**Comment by hborghols** [comment]
you can name it `chicks`

**Comment by woutsluiter** [comment]
Aaaah that's low man 🔪
