### ISSUE TITLE
Spinner component

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#269]
Blocks #270 

### Is your feature request related to a problem? Please describe ⚡️
We're missing ways to indicate a loading state when saving a form or validating a textfield. Right now a text replacement like "...Almost done" along with a disabled state is used, but this is not ideal. The background switch is too heavy and with long during requests it looks like the application froze.

### Describe the solution you'd like ✨
To indicate loading states with continuous feedback we want to use an animated spinner. Basically we want this: https://evergreen.segment.com/components/spinner. It uses a svg with a circle component which has an css animation on the stroke-dash-offset for the elastic effect. It should also have a `color` prop so it can be used in different contexts.

### Describe alternatives you've considered 🎡
A progressbar would also be nice, but not suitable for an indeterminate loading state

**Comment by nicokoelewijn** [comment]
Might i suggest a button containing theses dots: https://codepen.io/danielmorosan/pen/XmYBVx once it is pressed. Though this will probably be a decision for the design team :)

**Comment by woutsluiter** [comment]
Yes you might, but after a discussion with Luuk seems the spinner was the winner.
