### ISSUE TITLE
Supports tuples on padding/margin on Box

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#280]
### Is your feature request related to a problem? Please describe ⚡️
It would be cool if we could replace `trbl` with just tuples. `trbl` seems a bit of a useless abstraction after using it for a while. The general (if not only) use-case for it is when using it for padding/margin on a box. Original intent of it was that we could also use it for things like css' top,right,left and bottom properties. But it doesn't really seem to be used for that.

### Describe the solution you'd like ✨
This would turn:
```ts
import trbl from ...

<Box padding={trbl(0,12)} />
```
Into:
```ts
<Box padding={[0,12]} />
```
Which would just internalize the use of trbl on the Box's padding/margin.

We could easily maintain backwards compat as well by checking for Array.isArray on both padding/margin props and applying trbl or not for objects.

**Comment by hborghols** [comment]
I would not miss trbl if it were abstracted away so I'm all for it 👍

**Comment by woutsluiter** [comment]
It's got my vote 👍
