### ISSUE TITLE
The wrong color is used for TextField and TextArea

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#281]
### Bricks version 📦
0.6.4

### Describe the bug 🔍
The wrong color is used for TextField and TextArea for the MosTheme. This should be: `#333740` (grey base).

### Screenshots 📸
![screenshot 2018-12-17 at 16 57 56](https://user-images.githubusercontent.com/6347900/50098897-25067c80-021d-11e9-99bd-ad75649fe7f3.png)

**Comment by nicokoelewijn** [comment]
I could be mistaken, but i think this was edited in this PR: https://github.com/MyOnlineStore/bricks/issues/241

**Comment by CarloPalinckx** [comment]
This has been resolved, the published storybook seems out of date 👍
