### ISSUE TITLE
Add a component that styles html children

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#295]
### Is your feature request related to a problem? Please describe ⚡️
It would be nice if there was a component that styled a couple of common html tags. This could be used with things like wysiwyg editors that tend to use html as output. Html tags to consider:
- `a`
- `b`/`strong`
- `i`

### Describe the solution you'd like ✨
I suggest a component that does nothing more than apply contextual styling to these html tags. I would like some feedback on what to call it. It could also contain the actual implementation of `dangerouslySetInnerHtml`.

### Describe alternatives you've considered 🎡
We could also consider putting this behavior into a component like `Text` with maybe a `html` prop that gets wrapped with the contextual styling.

### Additional context 🖼
This would ultimately also replace things like #293

**Comment by hborghols** [comment]
I'm not sure if I totally get what this component is supposed to do. Is it supposed to show `<b>strong text</b>` as **`<b>strong text</b>`**?

**Comment by CarloPalinckx** [comment]
Closing this until it pops up again
