### ISSUE TITLE
Toaster manager

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#296]
### Is your feature request related to a problem? Please describe ⚡️
We need a way to manage multiple Toaster notifications so that they're not rendered on top of each other. Besides that a globally exposed api for adding notifications will enable us to use the Toaster for other cases like successful/failed requests.

### Describe the solution you'd like ✨
Rename the current `Toaster` to `Toast` and create a new `Toaster` which manages an array of notifications. The api can be something like:
```
toaster.notify(message: string)
toaster.success(message: string)
toaster.warning(message: string)
toaster.danger(message: string)
```

### Describe alternatives you've considered 🎡
A separate manager as a prop, but that would have more impact.

### Additional context 🖼
The BreakPointProvider can be used in the new `Toaster` instead of a BPP in every `Toast`. Each `Toast` still manages it's own timer, but also executes a `onRemoved` callback to remove it from the array (passed to the `onExited` of the `Transition`). An idea on how to handle smooth animations, see: https://github.com/segmentio/evergreen/tree/master/src/toaster/src

**Comment by CarloPalinckx** [comment]
Would be cool if could provide a global type with those methods somehow

**Comment by woutsluiter** [comment]
Ah yes. But the types in are automatically generated right?

**Comment by hborghols** [comment]
How do you think it should work in terms of UX? The same as evergreen, so displaying the notifications above each other, latest on top? 

And do I interpret it correctly that you still only want to expose `Toaster` to the world but let it use `Toast` internally for the individual messages?

**Comment by CarloPalinckx** [comment]
> Ah yes. But the types in Bricks are generated right?

Correct, but you want the window to contain extra properties if bricks is imported. Which could be a bit tricky.

We could still consider a `injectToaster` HOC (or hook for that matter) which just injects the toaster as a prop.

**Comment by CarloPalinckx** [comment]
Actually, instead of smashing it onto the window we could just export a singleton from the package which also solves the typing struggles.

**Comment by woutsluiter** [comment]
So that singleton would attach itself the window then if not present?

**Comment by woutsluiter** [comment]
>How do you think it should work in terms of UX? The same as evergreen, so displaying the notifications above each other, latest on top?
I'll check with UX.

>And do I interpret it correctly that you still only want to expose Toaster to the world but let it use Toast internally for the individual messages?
I think it would be enough to only export the Toaster. We could always export it separately if needed.

**Comment by hborghols** [comment]
Cool that sounds good 👍
