### ISSUE TITLE
Component Wishlist ✨🙏

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#31]
- [x] **Flex/Row**
Provides an abstraction for the position of components.
- [x] **ButtonGroup**
Could help with alignment of multiple buttons for responsive views.

- [x] **Scrollable**
Would be nice if we could provide a consistent way to add scrolling behavior to components.

- [x] **Modal**
For opening/closing pop-ups.

- [x] **Toaster**
For showing fixed notifications.

- [x] **Form elements**
We could use a set of form elements.

- [x] **Separator**
A component that eithers wraps and provides a border or that is rendered without children to provide just a seperating line.

**Comment by nicokoelewijn** [comment]
Form elements is a bit ambiguous, which elements should exactly be created?

**Comment by CarloPalinckx** [comment]
I think we are pretty close to a complete set. A few that pop up in my mind are: `DatePicker` `ColorPicker`(?), a handfull of texfield formatters maybe. Maybe you could work out a list of thing you'd like to see?
