### ISSUE TITLE
Provide a fallback for missing theme properties

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#311]
### Is your feature request related to a problem? Please describe ⚡️
When using Bricks components without defining its theme props explicitly an error is thrown. Wrapping theme's in each other apparently does not work.

### Describe the solution you'd like ✨
The `MerchantTheme` could do the same as `Contrast`: deepmerging its themeObject with our MosTheme.

### Describe alternatives you've considered 🎡
Entering all theme options in the monolith and trying to keep up with changes. Ain't nobody got time for that!

**Comment by CarloPalinckx** [comment]
Would this issue be solved with the proposed solution in #325  ?

**Comment by woutsluiter** [comment]
Depends on the implementation, but if it would have something like a default/fallback set that is deep-merged then yes, it would

**Comment by hborghols** [comment]
This could already be implemented without waiting on #325 right?
