### ISSUE TITLE
Seperate font definitions in theme

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#33]
Button and Notifications now share the font size. In the current MOS styling however these are two different sizes (16px . and 14px) where the notification font-size follows the body font-size.

To fix this the theme settings should be adjusted with font settings according to this [proposal](https://gist.github.com/woutsluiter/d661a2348b1b2c07f2d42b80d1da8667).

**Comment by CarloPalinckx** [comment]
duplicate of #20
