### ISSUE TITLE
Build can't be imported in 1.x

### ISSUE THREAD

**Issue by hborghols** [MyOnlineStore/bricks#333]
### Bricks version 📦
`1.x` rc branch

### Describe the bug 🔍
When running a build on the `1.x` branch and trying to link the package to another project I discovered that the generated build can't be imported yet. This probably has something to do with the new webpack config and switching to `lib` instead of `dist` as output dir.

### To Reproduce 💥
1. Check out `1.x`
2. Generate a build
3. Try to import the generated package

### Expected behavior ✨
Fancy new bricks in my fancy new project

**Comment by woutsluiter** [comment]
Seems like a simple fix by changing L180 of `package.json` to lib

**Comment by hborghols** [comment]
It doth fixes it

**Comment by woutsluiter** [comment]
Fixed in #334
