### ISSUE TITLE
Storybook does not work in IE

### ISSUE THREAD

**Issue by hborghols** [MyOnlineStore/bricks#337]
### Bricks version 📦
0.10.1

### Describe the bug 🔍
Storybook doesn't render in IE. There's some discussion about this here: https://github.com/storybooks/storybook/issues/4099 

It might have something to do with the specific version of storybook that we're using. The current official storybook version seems to work fine in IE (https://storybooks-official.netlify.com/).

The following errors are thrown in the console:
![screenshot 2019-02-19 at 17 11 51](https://user-images.githubusercontent.com/23050817/53029584-7de6d100-3469-11e9-8d28-b84d9cc174e4.png)

### To Reproduce 💥
1. IE
2. Go to storybook

### Screenshots 📸
![screenshot 2019-02-19 at 17 07 22](https://user-images.githubusercontent.com/23050817/53029321-dc5f7f80-3468-11e9-866f-6a280693f1ba.png)

### Context👨‍💻
 - IE11

**Comment by woutsluiter** [comment]
Works again 🎉
