### ISSUE TITLE
Move mouse event to onClick for CheckBox

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#340]
### Is your feature request related to a problem? Please describe ⚡️
Currently the Checkbox adds a mouse event to the onChange callback. Hover this blocks us from properly adding a change event. We should consider an onClick prop that allow you to do this. This is internally used for checking multiple checkboxes in the Table

**Comment by hborghols** [comment]
I don't really get the request described here. What do you want to add a change event too? Why is there a mouseEvent in the callback in the first place and where should an onClick prop be added?

**Comment by hborghols** [comment]
Works :D
