### ISSUE TITLE
Replace BreakPointProvider with react-measure

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#344]
It would be great if we could remove the BPP in favor of react-measure. It also ships with a resize observer polyfill. Meaning that we could remove our dependency on it. Instead of shipping our own it would mean that we will have to add react-measure as a peerDep. Otherwise it could end up being shipped twice. It could be our recommended tool to deal with responsiveness.

**Comment by hborghols** [comment]
Resolved in https://github.com/MyOnlineStore/bricks/pull/346
