### ISSUE TITLE
Add classnames to components for backwards compatibility with regular css

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#37]
Since we use `styled-components` for this all the component classNames will get scrambled which is a very good thing because it gets rid of the global aspect of regular css. However since we also allow custom css editing we might want to think about adding a css hook so that they still are stylable from the css-editor.

**Comment by CarloPalinckx** [comment]
So for now we will be adding className to the components, these should never be used for styling inside this codebase ❗️But are purely there for backwards compatibility for the css-editor until we can sunset it. We should use the function/class displayName. (i.e. `.Button` or `.Notification`).

**Comment by hborghols** [comment]
Are we still going to do this or is this plan definitively cancelled?

**Comment by CarloPalinckx** [comment]
This issue doesn't really require any focus atm.

**Comment by CarloPalinckx** [comment]
Closing this for now, it will resurface if this becomes more urgent.
