### ISSUE TITLE
Skeletons are not rendered properly in a FormRow

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#382]
### Bricks version 📦
1.0.3

### Describe the bug 🔍
When using a skeleton in combination with the form row (ie: `<FormRow label={<Skeleton.Text baseWidth={70} lines={1} />} field={<Skeleton.Rect width={'100%'} />} />`. You are shown a label skeleton with minimal width.

### Expected behavior ✨
Nothing more than `<FormRow label={<Skeleton.Text baseWidth={70} lines={1} />} field={<Skeleton.Rect width={'100%'} />} />` should be needed to render a formrow skeleron

**Comment by CarloPalinckx** [comment]
@woutsluiter I think this was introduced by #370. Would you mind taking a look at this?

**Comment by hborghols** [comment]
Sure, I'll take a look at is when I have some time
