### ISSUE TITLE
Popover issue

### ISSUE THREAD

**Issue by nicokoelewijn** [MyOnlineStore/bricks#391]
### Bricks version 📦
1.2.0

### Describe the bug 🔍
In some situations the Popper from the Popover component stays in the viewport. This is not the desired behaviour. I found a similar issue here: https://github.com/FezVrasta/react-popper/issues/16. According to this issue the problem can be resolved by updating the version. 

### To Reproduce 💥
I haven't been able to reproduce this error in Bricks though it does occur when used outside of the library. 

### Expected behavior ✨
The Popper should stick to the button around which it is wrapped. 

### Screenshots 📸
![Screenshot 2019-06-03 at 17 21 52](https://user-images.githubusercontent.com/4093202/58813470-250c0480-8624-11e9-8a12-09ee975281f8.png)

### Context👨‍💻
 - Device: MacBook Pro
 - OS: OSX
 - Browser Chrome
 - Browser version 74.0.3729.169

**Comment by CarloPalinckx** [comment]
Does your window end where your screenshot ends? Which makes it get pushed up?

**Comment by nicokoelewijn** [comment]
> Does your window end where your screenshot ends? Which makes it get pushed up?

Yes, for some reason it stays in the browser viewport

**Comment by nicokoelewijn** [comment]
Turns out this is rather an implementation error than an error in the component. This issue can be resolved with the preventOverflow prop: `preventOverflow={false}`
