### ISSUE TITLE
Modals like toaster

### ISSUE THREAD

**Issue by nicokoelewijn** [MyOnlineStore/bricks#405]
### Is your feature request related to a problem? Please describe ⚡️
A page can contain many modals, but it never happens that multiple modals are used at once. The modals are rendered and set to invisible with css, so the nodes remain in the dom tree. These modals exist but might never be used.

### Describe the solution you'd like ✨
Like the Toaster component there should be only one modal. This modal receives render props to render the contents.

### Describe alternatives you've considered 🎡
Another way i thought about was by managing the mounting and un-mounting the modal when required but this might impact the loading time and it's bit harder to enforce the mouting and unmounting of modals.

**Comment by CarloPalinckx** [comment]
This looks useful! would you mind adding a proposed API to this RFC so I can have a look at that?

**Comment by hborghols** [comment]
> This looks useful! would you mind adding a proposed API to this RFC so I can have a look at that?

Seconded 😄

**Comment by woutsluiter** [comment]
Aye

**Comment by nicokoelewijn** [comment]
Thanks for the enthusiasm!
The new modal component will be called **ModalManager**, so it can exists aside the old modal (no breaking changes). 

The modal can be created/triggered by calling the `window.modal.render` function. This function expects the same props as the current implementation, with the addition of renderContent. The renderContent is the main content of the modal.  

```
`window.modal.render({
 title: string …
 rendercontent(): JSX.Element
})`
```

With the show prop you can choose to either create it and keep it hidden (`show: false`) or render it immediately (`show: true`). 
The visibility of the modal can be toggled programmatically by calling `window.modal.toggle({show: boolean})`.

For more details please check the sample branch: https://github.com/MyOnlineStore/bricks/tree/ModalManager

**Comment by CarloPalinckx** [comment]
I think this looks pretty solid. I'm having some doubts about the toggle tbh. I think you'll end up with weird side-effects if you have multiple sources of truth about the shown state. This is different from the Toasts since they are used to do static, one-off messages. The modals are used more dynamically with changing content and form etc. Another option would be that we build the API as if it were a one-off action that we memoize with useEffect.

**Comment by CarloPalinckx** [comment]
>  Another option would be that we build the API as if it were a one-off action that we memoize with useEffect.

NVM. That would get hairy quick, since you need to memoize the renderContent callback with is pretty awkward.

**Comment by CarloPalinckx** [comment]
Closing this because of a lack of bandwidth for this addition
