### ISSUE TITLE
Implement primary variants for Link

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#412]
### Is your feature request related to a problem? Please describe ⚡️
Currently, we lack a way to bump the visual priority on the Link component. In cases where the button is too clunky. You want to use color to prioritise links.

### Describe the solution you'd like ✨
After some careful consideration we came up with a new pattern. Primary links. These will have a prop `variant="primary"` just like buttons. Which would render an alternate styling.

**Comment by woutsluiter** [comment]
Don't think I've really seen this pattern before. 🤔 At least not within a paragraph. Do you have an example/use-case? But if UX thinks it's the way to go I don't have technical issues with it. Though I would opt for a very limited set to prevent a Link Carnival. `primary` and `inherit` for example.

**Comment by CarloPalinckx** [comment]
I'll get some examples to you tomorrow 👍

**Comment by CarloPalinckx** [comment]
It could be used to create a uniform API for design patterns like this:

- ![Screenshot 2019-07-24 at 09 59 52](https://user-images.githubusercontent.com/6347900/61775958-47d3c180-adfa-11e9-9dec-e4fc179e11c8.png)
- ![Screenshot 2019-07-24 at 09 58 47](https://user-images.githubusercontent.com/6347900/61775960-47d3c180-adfa-11e9-90d6-8f98a3462079.png)
- ![Screenshot 2019-07-24 at 09 54 11](https://user-images.githubusercontent.com/6347900/61775961-47d3c180-adfa-11e9-86b1-e83a2d5bc007.png)

When a button is too bulky and when a Link does not stand out visually enough. After giving it some thought I think we should maybe opt for a TextualButton component instead of a Link variant. What do you think @woutsluiter ?

**Comment by hborghols** [comment]
Opting for something like a `TextualButton` sound better to me than adjusting `Link`. Imo Link should remain a very simple link component. The intended use of this proposal is more in the direction of a button (also seen by the chevron icon in your example). In terms of implementation it could be a `styled(Link)` though I guess 🙂

**Comment by CarloPalinckx** [comment]
Alright, TextualButton. It is 👍
