### ISSUE TITLE
Progress component

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#428]
### Is your feature request related to a problem? Please describe ⚡️
This rfc is a bit of a package deal with the carousel component #429. We could use a pattern that lets us render dots with pagination, to avoid possibly having to deal with a large amount of pages/slides.

### Describe the solution you'd like ✨
A suggested api would be:

```jsx
<Pagination 
    total={props.slides.length}
    maxShown={4} // with a default setting
    currentIndex={props.currentIndex}
    onClick={clickedIndex => {
        // navigate to slide at index
    }}
/>
```

### Describe alternatives you've considered 🎡
Alternative name could be `Indicator` or `Progress`

### Additional context 🖼
The current design for this:
![Screenshot 2019-08-26 at 16 10 26](https://user-images.githubusercontent.com/6347900/63696945-2b251200-c81c-11e9-902f-ca7adc8457f1.png)

**Comment by woutsluiter** [comment]
Not sure if there is a use case for this component outside a Carousel type component. I mean, if it's for a wizard type component I think you would want to differentiate between previous/completed steps and next/uncompleted steps. Or maybe a different look all together. What do you think @LuukHorsmans?

**Comment by LuukHorsmans** [comment]
I agree that there is probably going to be a difference. I can see dots being used as indicators in different use cases, but maybe as a variant without the pagination and with completion-tracking. For example I'm working on a registration flow with 4 screens: 
![image](https://user-images.githubusercontent.com/44433296/63699109-7d683200-c820-11e9-8796-3f03cd735edd.png)

**Comment by hborghols** [comment]
I would suggest that the `Dots` here are a rather a `Pagination` or `Pages` component (or something similar). If we separate it from the Carousel it should support all the desired use cases, including maybe numbered pages (for example for a product overview page). The fact that the pages are rendered as dots is just a visual detail imo.

**Comment by CarloPalinckx** [comment]
`Pagination` sounds good imo 👍

**Comment by hborghols** [comment]
Cool, in that case I think the API looks good for now. I think we can extend on it if and when we need to.

**Comment by CarloPalinckx** [comment]
![image (8)](https://user-images.githubusercontent.com/6347900/63865564-167a8280-c9b2-11e9-8f7a-20d0fffc4a3f.png)
There is also a usecase for a numeric version ⤴️

**Comment by woutsluiter** [comment]
>There is also a usecase for a numeric version

I think I misunderstood your initial post, thinking it would only be Dots.

**Comment by hborghols** [comment]
Then we need an addition to the api which determines the rendering of the page buttons. We could possibly also allow a custom rendering

**Comment by LuukHorsmans** [comment]
Because both options use widely different logic we have decided to split these options into:

- Pagination:
![image](https://user-images.githubusercontent.com/44433296/64015120-1bf7da00-cb24-11e9-8fdf-5c24b3019747.png)

- Progress:
![image](https://user-images.githubusercontent.com/44433296/64015138-2b772300-cb24-11e9-88c3-9a2a05417133.png)

**Comment by hborghols** [comment]
Seems reasonable 👍
