### ISSUE TITLE
Carousel component

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#429]
### Is your feature request related to a problem? Please describe ⚡️
Currently there is not really a standardised way to show a carousel in any of our applications. Because this a pattern that can be useful across multiple applications. I suggest we bring it over here. 

### Describe the solution you'd like ✨
I suggest a component with the following api:

```jsx
// controlled example
const App = () => {
    const [currentIndex, setIndex] = useState(0);

    return (
        <Carousel
            loop // wether the carousel returns to the first slider after pressing next on the last slide. (and vice-versa)
            currentIndex={currentIndex} // index of current slide. Can also be undefined if you don't want to control the index yourself.
            onChange={newIndex => {
                setIndex(newIndex);
            }}
            // optional, onChange would probably suffice in most use cases
            onForward={newIndex => {
                setIndex(nextIndex);
            }}
            // optional, onChange would probably suffice in most use cases
            onBackwards={newIndex) => {
                setIndex(nextIndex);
            }}
            // optional
            onClick={clickedIndex => {
                // can be used to highlight image for example
            }}
        >
            // any reactnode could be used in the carousel
            <span>slide 0</span>
            <span>slide 1</span>
            <span>slide 2</span>
        </Carousel>
    );
};
```

```jsx
// uncontrolled example
const App = () => {
    return (
        <Carousel loop>
            <span>slide 0</span>
            <span>slide 1</span>
            <span>slide 2</span>
        </Carousel>
    );
};
```

### Things I'd like feedback on 🎡
The carousel commonly has dots accompanying them. Not sure if we should internalise these are if we should have a separate Dots component. The dots can be pretty complex themselves because they need to be "paginated" (like on instagram) to prevent 100 of dots.

### Additional context 🖼
There are currently 2 designs for this:

![Screenshot 2019-08-26 at 15 29 42](https://user-images.githubusercontent.com/6347900/63694283-63c1ed00-c816-11e9-9794-4c6134733e5f.png)
![Screenshot 2019-08-26 at 15 29 32](https://user-images.githubusercontent.com/6347900/63694284-63c1ed00-c816-11e9-9cb7-afb799e21f54.png)

Maybe @LuukHorsmans could chime in on the hover, click behaviour etc.

**Comment by woutsluiter** [comment]
I guess the question is would you use the dots for anything else? Otherwise it would fit well in the component itself, even if it has high complexity (which could be added with iterations).

**Comment by woutsluiter** [comment]
Have you considered any library?

**Comment by CarloPalinckx** [comment]
> Have you considered any library?

Framer motion has a pretty simple example with this functionality. This would have to be a major release tho.

**Comment by woutsluiter** [comment]
>This would have to be a major release tho

What would make it a breaking change?

**Comment by hborghols** [comment]
API looks good 👍. I will comment on the dots in the other RFC.

**Comment by CarloPalinckx** [comment]
> What would make it a breaking change?

Carousel would always be exported because of the single entry -> Carousel imports framer-motion -> framer-motion undefined in client application -> 💥
