### ISSUE TITLE
Revisit usage of severity="info" on the Text component.

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#431]
### Is your feature request related to a problem? Please describe ⚡️
Currently the severity="info" prop is being abused as a "subdued"/"descriptive" style. We should consider adding a prop that matches this pattern and refactor all info="severities" to that.

**Comment by Dreamdealer** [comment]
When a light grey color is set as a severity color (e.g. #A6AAB3 in storefronts), the text is rendered in the correct color, but other elements that might use this color are way too light, for example the  info toaster.

**Comment by hborghols** [comment]
@CarloPalinckx would it suffice (for now) to restore the `descriptive: boolean` prop we used to have with the current MosTheme styling for `severity='info'`?

**Comment by hborghols** [comment]
So basically like this: https://github.com/MyOnlineStore/bricks/blob/68ffe434f5656cdc7b9d88a9e947ccc706b018c5/src/components/Text/index.tsx + https://github.com/MyOnlineStore/bricks/blob/68ffe434f5656cdc7b9d88a9e947ccc706b018c5/src/components/Text/style.tsx

**Comment by Dreamdealer** [comment]
Yes.

**Comment by CarloPalinckx** [comment]
I would want to avoid, having both the descriptive and severity prop tbh. Since this would make the coloring multi-dimensional since you would also have severity=error + descriptive, with one of the two overwriting the other. Maybe design could chime in a bit on how they would tackle this?

**Comment by hborghols** [comment]
What would your preference be? Severity="descriptive"? Or do away with severity alltogether? I think we have to decide on our implementation preference before asking design t.b.h.

**Comment by hborghols** [comment]
Alright it came up and design is looking at forms today so we will have a definitive answer tomorrow. But it looks like `descriptive` and the different severity levels will never overlap. So that would encourage implementing it as one prop. All that remains then is deciding on naming. The way I see it there are two options for the prop type:

`severity: "descriptive" | "error" | "info" | "warning" | "success"`

or something like:

`textStyle: "descriptive" | "severity-error" | "severity-info" | "severity-warning" | "severity-success"`

Any thoughts?

**Comment by Dreamdealer** [comment]
I prefer `textStyle` since a descriptive text has nothing to do with severity.

**Comment by woutsluiter** [comment]
I like the shorter values, but with the prop `textStyle`

**Comment by hborghols** [comment]
I think I like the shorter values together with `textStyle` as well. I agree that descriptive is unrelated to severity. We could use `textStyle` and type it as `TextStyleType = SeverityType & "desciptive"`. That way we get the shorthand values and we still type the severities in a general place. This would work for me 🙂

**Comment by CarloPalinckx** [comment]
Don't you think `textStyle` suggests that it changes more than just the color? Which it doesn't?

**Comment by CarloPalinckx** [comment]
What about a `variant` prop with the short values? Basically like we do for `Button`?

**Comment by hborghols** [comment]
Sure `variant` works for me 👍

**Comment by woutsluiter** [comment]
But there already is a `variant` prop. Would you suggest to expand this with the new types?

**Comment by hborghols** [comment]
Right that's true 😓. I agree with renaming those to `size`. That makes more sense to me

**Comment by hborghols** [comment]
Implemented in `2.x`
