### ISSUE TITLE
Raised styling is not workable

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#438]
### Bricks version 📦
1.13.0

### Describe the bug 🔍
Working with raised Raised causes problems the following
- it has no background color, but it does have padding. This way you can only properly set a background color via inline `style`, because a child with a background color doesn't fill the full box.
- having a styled width of 100%, but no `box-sizing` property causes it to expand its parent.

### Expected behavior ✨
Raised only manages the depth of an element, not the content. Otherwise it might as well be a Modal or something. And it stays within the parent dimensions.

### Proposed solution
I propose to remove the `padding` and add `box-sizing: border-box`

**Comment by CarloPalinckx** [comment]
Yes please 🙏

**Comment by woutsluiter** [comment]
Only thing is it might be a visually breaking change. But then again I don't think it's used that much. I'll check it out.

**Comment by woutsluiter** [comment]
On second thought I think it is best to remove the `width` as well. That should be managed with a `Box`

**Comment by hborghols** [comment]
👍 🆗 🚯 ✅ 🎉
