### ISSUE TITLE
FoldOut cuts of pseudo-class styles of children

### ISSUE THREAD

**Issue by hborghols** [MyOnlineStore/bricks#442]
### Bricks version 📦
1.15.1

### Describe the bug 🔍
Because `overflow: hidden;` is set within `FoldOut`, pseudo-class styles of children such as the focus state of the `Button` get cut off.

### To Reproduce 💥
1. Create a Button within a FoldOut
2. Focus the Button
3. The focus state is cut off

### Expected behavior ✨
The focus state should be fully visible

### Screenshots 📸
![image-20190923-125025](https://user-images.githubusercontent.com/23050817/65499447-e72a3900-debd-11e9-8423-295f5880f744.png)

### Proposed solution:
I propose adding an optional `overflow` prop to `FoldOut` that can be set to `"hidden" | "visible"`. The default style would still be `hidden` but it would make it possible to set it to visible.

### Context👨‍💻
 - Everywhere

**Comment by woutsluiter** [comment]
Visible when folded out right? 😄 yeah I guess that would work.

**Comment by hborghols** [comment]
> Visible when folded out right? 😄 yeah I guess that would work.

Yep 😄, otherwise it might be slightly problematic 😬

**Comment by CarloPalinckx** [comment]
Shouldn't visible just be default behaviour? If you want to hide whatever breaks out you can still add a Box around that with hidden

**Comment by hborghols** [comment]
Yeah I think you're right. I will make visible when open the default behavior 👍

**Comment by hborghols** [comment]
I will revisit this soon (when I have time). Just setting overflow to visible on props.isOpen messes up the animation as it immediately shows the contents that are folding out. So some sort of delay should be built in.
