### ISSUE TITLE
Add a 'direction' prop to ButtonGroup

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#454]
### Is your feature request related to a problem? Please describe ⚡️
With the current ButtonGroup you cannot switch the direction/responsive behaviour of the ButtonGroup other than opting in/out of stacking behaviour.

### Describe the solution you'd like ✨
Would be nice if we could provide some way to switch the direction of the rendering of the button. 

```
<ButtonGroup direction="rtl | ltr">
  <Button variant="primary" />
  <Button variant="secondary" />
</ButtonGroup>
```

### Describe alternatives you've considered 🎡
We could also opt for something more ambiguous that does not represent physical appearance:

```
<ButtonGroup direction="forward | backwards">
  <Button variant="primary" />
  <Button variant="secondary" />
</ButtonGroup>
```

```
<ButtonGroup reversed>
  <Button variant="primary" />
  <Button variant="secondary" />
</ButtonGroup>
```

A nicer solutions perhaps would be:

```
<ButtonGroup direction="rtl | ltr | stacked">
  <Button variant="primary" />
  <Button variant="secondary" />
</ButtonGroup>
```
But this would "ideally" be a breaking change because we could replace the stacked boolean prop with this.

Update:

To avoid breaking changes, this would be my preferred solution:

```
<ButtonGroup stacked direction="rtl | ltr | stacked">
  <Button variant="primary" />
  <Button variant="secondary" />
</ButtonGroup>
```

Where we deprecate the stacked boolean in favour of direction="stacked" and remove it in 3.0

**Comment by hborghols** [comment]
Seems fine to me 👍. I definitely prefer describing it in a unambiguous way that directly relates to the physical appearance and it's nice to avoid breaking changes.

**Comment by woutsluiter** [comment]
I agree with Henk here and prefer last solution as well 👍

**Comment by CarloPalinckx** [comment]
FYI: I've also made the issue to remove the deprecation and scheduled it for milestone 2.0.0 #455
