### ISSUE TITLE
Add support for "media" to Modals

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#458]
### General concept of your idea, what purpose does it serve?

Because a lot of modals already contain some form of media, we should add support for this with something like a prop. These types of placement should be supported.
https://sketch.cloud/s/RAxwQ/a/KQpxkV

### How does this relate to current implementations?

This would be an addition to the current implementation. There should be support for media with multiple placements and there should be support for a centered button.

**Comment by CarloPalinckx** [comment]
I suggest the following props be added to the Modal:

```
<Modal
  title="Some title"
  media={<img src="/foo.jpg" />}
  bleedMedia={true|false}
  size="small | medium | large"
>
    Some content
</Modal>
```

**Comment by Dreamdealer** [comment]
I'd like that the positioning/layout of the media element isn't fixed to bleeding which is the only option with this `bleedMedia` prop. I'd prefer something like `mediaLayout` which has a enum list of options like `media-right-bleed` or `media-top` or `media-collapsed` or whatever the future might bring. This limits the amount of props needed to create more complex layouts and provides a more future proof setup.

**Comment by CarloPalinckx** [comment]
> I'd like that the positioning/layout of the media element isn't fixed to bleeding which is the only option with this bleedMedia prop. I'd prefer something like mediaLayout which has a enum list of options like media-right-bleed or media-top or media-collapsed or whatever the future might bring. This limits the amount of props needed to create more complex layouts and provides a more future proof setup.

I kept it a boolean because the left/right alignment is based on what size the modal has. According to the design:

- A large modal always has its media aligned right.
- A medium or small modal always has it's media aligned above the title. 

I'd honestly prefer a stricter set up to limit the number of modals the system has for the sake of maintainability and consistency (and possible also sanity 😄 ). I think adding an easy to "just add a variation" would do more harm than the bool. Don't you agree?

**Comment by Dreamdealer** [comment]
Yeah, you're right... I tend to always think too far ahead _and_ assume that a lot of variations will be needed sooner or later. This is a thing of the past, luckily.
