### ISSUE TITLE
Rename/Remove deprecated MerchantTheme > CustomTheme

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#459]
### Is your feature request related to a problem? Please describe ⚡️
`MerchantTheme` is derpecated in favor of a more generic `CustomTheme` and should no longer be exposed.

### Describe the solution you'd like ✨
Remove `MerchantTheme`  and rename `ExperimentalCustomTheme` to `CustomTheme`.

### Describe alternatives you've considered 🎡
Rename `MerchantTheme` to `CustomTheme`.

### Additional context 🖼
`MerchantTheme` and `ExperimentalCustomTheme` are practically the same: they deep merge the `theme` prop with the `mosTheme` object. It's the `genTheme` that is still experimental.

**Comment by hborghols** [comment]
Merged in `2.x`
