### ISSUE TITLE
Upgrade styled-components to v5

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#460]
Enable [BEASTMODE!!](https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987) 🦁

**Comment by CarloPalinckx** [comment]
v5 is still only a release candidate tho. Could plan the milestone around the actual release of v5.

**Comment by woutsluiter** [comment]
Right! Couldn't find an actual release date, but shouldn't be long now 🤞
