### ISSUE TITLE
Add color swatches to MosTheme

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#461]
### Is your feature request related to a problem? Please describe ⚡️
Our UX team is missing swatches in the current MOS design system. Moreover, the steps in the  current swatches are not spread evenly.

### Describe the solution you'd like ✨
Our UX team have created a new color system with additional swatches. These should be implemented in `MosTheme.ts`. To be able to use them in applications they should be exported as well.

```
import { colors } from '@myonlinestore/bricks';

const Component = () => <div style={{ color: colors.red700 }} />
```

### Describe alternatives you've considered 🎡
No

### Additional context 🖼
When this is implemented several components can be updated afterwards, like Button, Text, Badge and form elements.

**Comment by hborghols** [comment]
This has been implemented a while ago.
