### ISSUE TITLE
Add support for float values to `TextField.Number`

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#483]
### Is your feature request related to a problem? Please describe ⚡️
Currently the `TextField.Number` only supports integers. It would be great if it could handle floats as well in a localized format.

### Describe the solution you'd like ✨
Implement the `Intl.NumberFormat` like in `TextField.Currency` and add these props:
```typescript
    allowDecimals?: boolean;
    locale?: string;
    /** always format with this number of decimals if defined */
    minimumFractionDigits?: number; 
    /** limit the number of decimals if required */
    maximumFractionDigits?: number;
```

### Describe alternatives you've considered 🎡
Add a separate `TextField.Float` component, but seems redundant.

### Additional context 🖼
The `TaxForm` in Canopy has percentage fields which currently use a plain `TextField`. This however prevents the user entering a value in their own localized format. The value required server side is a Float (actually a String, but saved as a float).

**Comment by hborghols** [comment]
👍
