### ISSUE TITLE
Refactor TextField + formatters

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#490]
### Is your feature request related to a problem? Please describe ⚡️
We currently use static properties to allow easy access to multiple formatters of the textfield. However, this also forces us to use the class component lifecycle methods. 

### Describe the solution you'd like ✨
Perhaps we would do good if we would refactor these components into seperate components, this would also make them easier to code-split in the future.

Perhaps something like this could work:

```diff
- <TextField.Currency ... />
+ <CurrencyField ... />

- <TextField.Number ... />
+ <NumberField ... />

  <TextField ... />
```

**Comment by hborghols** [comment]
How do you propose to implement the separate `NumberField` and `CurrencyField`? One of the advantages of the current implementation is that the different fields are styled only once. 

What is the benefit of rewriting them apart from codesplitting? That is an advantage but not a huge one imo given the size of the component. It currently works fine with the class component lifecycle methods.

**Comment by hborghols** [comment]
`NumberField` and `CurrencyField` have been introduced in `2.x`
