### ISSUE TITLE
Provide alternative API for Select

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#548]
### Is your feature request related to a problem? Please describe ⚡️
The `Select` component houses a lot of props that get passed down to nested subcomponents within the `Select` itself. This get's pretty ambiguous over time when props would be added to support more complex behaviour.

A good example of this is the `data-testid`, we require only one props `data-testid` on the top level `Select` and then pass on `${data-testid}-input` and `${data-testid}-input-field` to subcomponents. Which makes it hard to trace the origin of the test-id's when a new user tries to grep the testid. 

Another case is to be made for props like `emptyText` and `placeholder` the intent of those props ins't directly clear. Once you would make the filter input optional, these both implicitly would become useless. I suggest a more explicit approach.

### Describe the solution you'd like ✨
By using a subcomponents approach, we can give more fine control over what is rendered and what each subcomponents requires as props. It also alligns more to how native html select + options work.

```tsx
<Select data-testid="foo" onChange={handleChange}>
    <Select.Filter
        data-testid="foo-filter"
        icon={<SearchIcon />}
        placeholder="search an option"
    />
    <Select.Modal>
        <Select.Option data-testid="foo-option-blue" value="blue">
            <Color hex="#000ff" /> Blue
        </Select.Option>
    </Select.Modal>
</Select>
```

We could use context to pass state between the subcomponents that (optionally) get rendered.

Select
```tsx
const SelectContext = createContext({...});

const Select = (props) => {
    const [filter, setFilter] = useState(null);
    return (
        <SelectContext.Provider value={{ filter, setFilter }}>
            {props.children}
        </SelectContext.Provider>
    );
}
```

Select.Filter
```tsx
const SelectFilter = props => {
    const { filter, setFilter } = useContext(Select.Context);

    return <input onChange={setFilter} value={filter} />
}
```

Select.Option
```tsx
const SelectOption = props => {
    const { filter } = useContext(Select.Context);
    
    if (props.value.indexOf(filter) === -1) {
        return null;
    }

    return <div>{props.children}</div>
}
```

This could also allow us to merge the Select and NativeSelect components if we could separate shared components into subcomponents.

### Additional context 🖼
https://primer.style/components/SelectMenu#selectmenufilter is a great example of how this could turn out.

Another case that would require an approach like this is when listing a nested tree list of items as options in the select. In the current scenario, you'd have to flatten that tree and assign a level to it. With the subcomponents approach you could recursively render them and group them in <Select.OptionGroup> component

### Migration strategy
We could probably build this backwards compatible because the difference between the implementations lies in the use of `props.children` or not. We could add a deprecation warning when a user did not provide any children.

**Comment by hborghols** [comment]
Good idea 👍. The use of subcomponents is a lot less opaque than the current implementation. At first glance I don't have any issues with the proposed API but I will mull it over and complain if I think of something 😛.
