### ISSUE TITLE
SelectModal positioning and content flow issues

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#575]
### Bricks version 📦
3.3.2

### Describe the bug 🔍
The positioning of a `SelectModal` is not calculated correctly when using custom rendering. It uses the height of the selected option, but should use the height of the search field instead. See screenshots.

Then there is another problem: the height of the selected option is taken out of the content flow when opened. This is because the selected option and the search field are rendered as one component (`SearchInput`), one replacing the other depending on state. Here lies the root of the problem: these two should not be one component at all. The selected option (or empty option) should always be rendered in the content to prevent content flow jumps. The search input has a direct relation to the list of options and thus should be rendered in the same place (or portal) as the SelectModal.

### To Reproduce 💥
1. Add some long content after the `Select` custom rendering story
2. Open the `Select`

### Expected behavior ✨
A select dropdown rendered as a whole.

### Screenshots 📸
![image](https://user-images.githubusercontent.com/10552400/87515538-455a1f80-c67c-11ea-97f3-b812736a955d.png)

### Proposed solution 💡
I want to seperate concerns: split up the `SearchInput` into a `SearchInput` and `SelectedOption`. Furthermore I want to split up the `SelectModal` into `SelectModal` and `SelectList`. You would get something like this:

```javascript
<SelectWrapper>
    {/* Only takes care of rendering a selected or empty option */}
    <SelectedOption />
    {/* Only takes care of positioning */}
    <SelectModal>
        {/* Only takes care of filtering */}
        <SelectInput />
        <SelectList />
    </SelectModal>
</SelectWrapper>
```

**Comment by CarloPalinckx** [comment]
Should be pretty doable with the most recent refactor of the Select 👍 , interested to see how it will turn out! Would love a review tag once a PR is available :)

**Comment by hborghols** [comment]
Sounds good 👍. Maybe you can change the story, or add a story, to add more content before and after the Select so we can spot other positioning bugs more easily.
