### ISSUE TITLE
Severity colors for Link

### ISSUE THREAD

**Issue by woutsluiter** [MyOnlineStore/bricks#605]
### Is your feature request related to a problem? Please describe ⚡️
Currently our Link component only has one color. This however makes it impossible to use it in a different color context like a Notification with a info severity.

![Link](https://user-images.githubusercontent.com/10552400/99658703-28858c80-2a60-11eb-97b3-df186ebf5d37.gif)

### Describe the solution you'd like ✨
Add an optional `context` prop to Link and nest the theme object like so:
```
    Link: {
        common: {
            color: 'inherit',
            textDecoration: 'underline',
            fontSize: fontSize.base,
        },
        hover: {
            default: colors.green400,
            error: colors.red900,
            info: colors.blue900,
            success: colors.yellow900,
            warning: colors.green400,
        },
    },
```

### Describe alternatives you've considered 🎡
- A `severity` prop instead of `context`, but I think `context` is more scalable.
- Just change the default and hover color to `inherit`, but UX would like to keep the green hover for default and a slightly darker hover color for the severity types.

### Additional context 🖼
I discussed this issue with @RianneSchaekens and she came up with this [design](https://www.figma.com/file/2su4SmtMfDMKZBGjb8t3my/Untitled?node-id=0%3A1).

**Comment by woutsluiter** [comment]
Alternative more elaborate theme object:
```
    Link: {
        default: {
            idle: {
                color: 'inherit',
            },
            hover: {
                color: colors.green400,
            },
        },
        error: {
            idle: {
                color: colors.red700,
            },
            hover: {
                color: colors.red900,
            },
        },
        info: {
            idle: {
                color: colors.blue700,
            },
            hover: {
                color: colors.blue900,
            },
        },
        success: {
            idle: {
                color: colors.green800,
            },
            hover: {
                color: colors.green900,
            },
        },
        warning: {
            idle: {
                color: colors.yellow700,
            },
            hover: {
                color: colors.yellow900,
            },
        },
    },
```

**Comment by hborghols** [comment]
I would prefer a `severity` prop I think. That would make it more consistent with our other components. If there are clear indications that more than the severity types will be needed it's a different story but if there aren't I prefer a prop name that we use for other components too. The less elaborate theme object looks good 🙂

**Comment by woutsluiter** [comment]
>The less elaborate theme object looks good

To be more consistent I'd prefer to end with css properties. The last version is more common in the theme object.
