### ISSUE TITLE
Improve documentation ✒️📄

### ISSUE THREAD

**Issue by CarloPalinckx** [MyOnlineStore/bricks#9]
We need to have a Readme with some information about:
- Running the application
- Contributing
- Contributors
- maybe some form of an issue template.

**Comment by hborghols** [comment]
Alright checklist to complete before 1.0:

- [x] issue template
- [ ] README up to date about how the application can be run/built/used
- [ ] Contributing? I vote we leave this out for now, if someone wants to contribute they can get in touch

**Comment by hborghols** [comment]
Alright so 1.0 has been released but it would still be sweet to have some documentation about the API of the components. I will try to look into that (again) sometime soon. It should be possible to get some tables in storybook or something like that.

**Comment by CarloPalinckx** [comment]
@hborghols I think we can close this right? With the addition of the docs site?

**Comment by hborghols** [comment]
Yeah definitely 👍. The docs site can still be improved upon but I don't think that needs to be discussed/determined in this issue.
